//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShoePOSProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inventory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Inventory()
        {
            this.InventoryImages = new HashSet<InventoryImage>();
            this.CustomerSales = new HashSet<CustomerSale>();
        }
    
        public int Id { get; set; }
        public string BarcodeNo { get; set; }
        public Nullable<int> BrandId { get; set; }
        public Nullable<int> SizeId { get; set; }
        public Nullable<int> CollectionId { get; set; }
        public Nullable<int> ColorId { get; set; }
        public Nullable<int> GenderId { get; set; }
        public Nullable<int> ShoeStyleId { get; set; }
        public string Price { get; set; }
        public string SalePrice { get; set; }
        public string Discount { get; set; }
        public string AvailableAt { get; set; }
        public Nullable<System.DateTime> InventoryDate { get; set; }
        public string extra1 { get; set; }
        public string extra2 { get; set; }
        public string extra3 { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<int> IsActive { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
    
        public virtual BSST BSST { get; set; }
        public virtual BSST BSST1 { get; set; }
        public virtual BSST BSST2 { get; set; }
        public virtual BSST BSST3 { get; set; }
        public virtual BSST BSST4 { get; set; }
        public virtual BSST BSST5 { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InventoryImage> InventoryImages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerSale> CustomerSales { get; set; }
    }
}
